[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = """        RENTAL = HEX('b18f43'),"""
position = "after"
payload = """
NIC_INCOGNITO = HEX("d0d0d0"),
NIC_INVERT = HEX("2f2f2f"),
NIC_TETO = HEX("e15d73"),
NIC_PLANTS = HEX("33cc00"),
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """  return G.ARGS.LOC_COLOURS[_c] or _default or G.C.UI.TEXT_DARK"""
position = "before"
payload = """
G.ARGS.LOC_COLOURS['nic_incognito'] = G.C.NIC_INCOGNITO
"""
overwrite = true
match_indent = true
